### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by glued** [glued/harpy#1]
- [ ] close harp when project is removed
- [ ] surge support
- [ ] read harp.json
- [ ] terminal output panel
- [x] multihost
- [ ] toolbar actions  [header](https://atom.io/docs/api/v1.6.0/Workspace#instance-addHeaderPanel) [footer](https://atom.io/docs/api/v1.6.0/Workspace#instance-addFooterPanel)
